[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source $HOME/.config/dein/plugins/deoplete.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
on_cmd = 'Denite'
depends = ['neomru.vim']
hook_source = 'source $HOME/.config/dein/plugins/denite.vim'
hook_add = '''
    " Prefix key
    nnoremap [denite] <Nop>
    nmap <Space>u [denite]

    " Keymap
    " Current direcotry files
    nnoremap <silent> [denite]c :<C-u>Denite file_rec<CR>
    " Buffer files
    nnoremap <silent> [denite]b :<C-u>Denite buffer<CR>
    " Grep files
    nnoremap <silent> [denite]g :<C-u>Denite -auto_preview grep<CR>
    " Grep cursor word
    nnoremap <silent> [denite]s :<C-u>DeniteCursorWord grep<CR>
    " Recent files
    nnoremap <silent> [denite]f :<C-u>Denite file_mru<CR>
    " Outline
    nnoremap <silent> [denite]o :<C-u>Denite outline<CR>
    " Command history
    nnoremap <silent> [denite]c :<C-u>Denite command_history<CR>
    " move insert mode
    inoremap <silent> <C-j> <C-g>
    inoremap <silent> <C-k> <C-t>

'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = 'denite.nvim'
on_event = 'TextYankPost'

